/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package duocucmaps.gui;

import duocucmaps.bl.pdrBL;
import duocucmaps.bl.salaBL;
import duocucmaps.bl.servicioBL;
import duocucmaps.dal.conexion;
import java.sql.ResultSet;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 56964
 */
public class frmPdr extends javax.swing.JFrame {
    DefaultTableModel modelo;
    /**
     * Creates new form frmPdr
     */
    public frmPdr() {
        initComponents();
        setLocationRelativeTo(this);
        String[] titulos = {"ID", "Nombre", "Ubicación", "Descripción", "Piso"};
        modelo = new DefaultTableModel(null, titulos);
        jTablePdr.setModel(modelo);
        this.mostrarDatos();
        this.limpiar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePdr = new javax.swing.JTable();
        jButtonSalir_Pdr = new javax.swing.JButton();
        jButtonVAM_Pdr = new javax.swing.JButton();
        jButtonAgregar_Pdr = new javax.swing.JButton();
        jButtonCancelar_Pdr = new javax.swing.JButton();
        jButtonEliminar_Pdr = new javax.swing.JButton();
        jButtonModificar_Pdr = new javax.swing.JButton();
        jTextFieldUbicacion_Pdr = new javax.swing.JTextField();
        jTextFieldNombre_Pdr = new javax.swing.JTextField();
        jTextFieldId_Pdr = new javax.swing.JTextField();
        jTextFieldDescripcion_Pdr = new javax.swing.JTextField();
        jTextFieldPiso_Pdr = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duocucmaps/recursos/DUOC-UCBlancoV.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(27, 27, 27))
        );

        jTablePdr.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTablePdr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePdrMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePdr);

        jButtonSalir_Pdr.setText("Salir");
        jButtonSalir_Pdr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalir_PdrActionPerformed(evt);
            }
        });

        jButtonVAM_Pdr.setText("Volver al menú");
        jButtonVAM_Pdr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVAM_PdrActionPerformed(evt);
            }
        });

        jButtonAgregar_Pdr.setText("Agregar");
        jButtonAgregar_Pdr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregar_PdrActionPerformed(evt);
            }
        });

        jButtonCancelar_Pdr.setText("Cancelar");
        jButtonCancelar_Pdr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelar_PdrActionPerformed(evt);
            }
        });

        jButtonEliminar_Pdr.setText("Eliminar");
        jButtonEliminar_Pdr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminar_PdrActionPerformed(evt);
            }
        });

        jButtonModificar_Pdr.setText("Modificar");
        jButtonModificar_Pdr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificar_PdrActionPerformed(evt);
            }
        });

        jTextFieldId_Pdr.setEditable(false);

        jLabel2.setText("ID:");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Ubicación:");

        jLabel5.setText("Descripción:");

        jLabel6.setText("Piso:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("MANTENEDOR DE PUNTOS DE SERVICIO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jButtonVAM_Pdr)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButtonSalir_Pdr)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldNombre_Pdr, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                                    .addComponent(jTextFieldUbicacion_Pdr)
                                    .addComponent(jTextFieldDescripcion_Pdr)
                                    .addComponent(jTextFieldPiso_Pdr)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonAgregar_Pdr)
                                .addGap(43, 43, 43)
                                .addComponent(jButtonEliminar_Pdr)
                                .addGap(42, 42, 42)
                                .addComponent(jButtonModificar_Pdr)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonCancelar_Pdr)))
                        .addContainerGap(35, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldId_Pdr, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(jLabel7)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldId_Pdr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNombre_Pdr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUbicacion_Pdr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDescripcion_Pdr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPiso_Pdr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAgregar_Pdr)
                    .addComponent(jButtonCancelar_Pdr)
                    .addComponent(jButtonEliminar_Pdr)
                    .addComponent(jButtonModificar_Pdr))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalir_Pdr)
                    .addComponent(jButtonVAM_Pdr))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgregar_PdrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregar_PdrActionPerformed
        // TODO add your handling code here:
        conexion objConexion = new conexion();
        
        pdrBL oPdr = recuperarDatosGUI();
        
        String strSentenciaInsert = String.format("INSERT INTO Pdr (id_pdr, nombre_pdr, ubicacion_pdr, descripcion_pdr, piso_pdr)"
                + "VALUES (null, '%s', '%s', '%s', '%s')", oPdr.getNombre_pdr(), oPdr.getUbicacion_pdr(), oPdr.getDescripcion_pdr(), oPdr.getPiso_pdr());
        
        objConexion.ejecutarSentenciaSQL(strSentenciaInsert);
        this.mostrarDatos();
        this.limpiar();
    }//GEN-LAST:event_jButtonAgregar_PdrActionPerformed

    private void jTablePdrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePdrMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount () == 1){
            JTable receptor = (JTable)evt.getSource();
            jTextFieldId_Pdr.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),0).toString());
            jTextFieldNombre_Pdr.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),1).toString());
            jTextFieldUbicacion_Pdr.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),2).toString());
            jTextFieldDescripcion_Pdr.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),3).toString());
            jTextFieldPiso_Pdr.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),4).toString());
        }
        jButtonAgregar_Pdr.setEnabled(false);
        jButtonModificar_Pdr.setEnabled(true);
        jButtonEliminar_Pdr.setEnabled(true);
    }//GEN-LAST:event_jTablePdrMouseClicked

    private void jButtonEliminar_PdrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminar_PdrActionPerformed
        // TODO add your handling code here:
        conexion objConexion = new conexion();
        
        pdrBL oPdr = recuperarDatosGUI();
        
        String strSentenciaInsert = String.format("DELETE FROM Pdr WHERE id_pdr = %d", oPdr.getId_pdr());
        
        objConexion.ejecutarSentenciaSQL(strSentenciaInsert);
        this.mostrarDatos();
        this.limpiar();
    }//GEN-LAST:event_jButtonEliminar_PdrActionPerformed

    private void jButtonModificar_PdrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificar_PdrActionPerformed
        // TODO add your handling code here:
        conexion objConexion = new conexion();
        
        pdrBL oPdr = recuperarDatosGUI();
        
        String strSentenciaInsert = String.format("UPDATE Pdr SET nombre_pdr = '%s'," + "ubicacion_pdr = '%s'," + "descripcion_pdr = '%s'," + "piso_pdr = '%s' WHERE id_pdr = %d"
                ,oPdr.getNombre_pdr(), oPdr.getUbicacion_pdr(), oPdr.getDescripcion_pdr(), oPdr.getPiso_pdr(), oPdr.getId_pdr());
        
        objConexion.ejecutarSentenciaSQL(strSentenciaInsert);
        this.mostrarDatos();
        this.limpiar();
    }//GEN-LAST:event_jButtonModificar_PdrActionPerformed

    private void jButtonCancelar_PdrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelar_PdrActionPerformed
        // TODO add your handling code here:
        this.limpiar();
    }//GEN-LAST:event_jButtonCancelar_PdrActionPerformed

    private void jButtonSalir_PdrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalir_PdrActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonSalir_PdrActionPerformed

    private void jButtonVAM_PdrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVAM_PdrActionPerformed
        // TODO add your handling code here:
        this.hide();
        Mantenedor mn = new Mantenedor();
        mn.setVisible(true);
    }//GEN-LAST:event_jButtonVAM_PdrActionPerformed
    public void mostrarDatos() {
        while(modelo.getRowCount()>0){
            modelo.removeRow(0);
        }
        conexion objConexion = new conexion();
        
        try {
            ResultSet resultado = objConexion.consultarRegistros("SELECT * FROM Pdr");
            while (resultado.next()) {
                System.out.println(resultado.getString("id_pdr"));
                System.out.println(resultado.getString("nombre_pdr"));
                System.out.println(resultado.getString("ubicacion_pdr"));
                System.out.println(resultado.getString("descripcion_pdr"));
                System.out.println(resultado.getString("piso_pdr"));
                
                Object[] oPdr = {resultado.getString("id_pdr"), resultado.getString("nombre_pdr"), resultado.getString("ubicacion_pdr"), resultado.getString("descripcion_pdr"), resultado.getString("piso_pdr")};
                
                modelo.addRow(oPdr);
            }
        }
        catch (Exception e){
            System.out.println(e);
        }
    }
    
    public pdrBL recuperarDatosGUI() {
        pdrBL oPdr = new pdrBL();
        int id_pdr = (jTextFieldId_Pdr.getText().isEmpty()) ?0 : Integer.parseInt(jTextFieldId_Pdr.getText());
        
        oPdr.setId_pdr(id_pdr);
        oPdr.setNombre_pdr(jTextFieldNombre_Pdr.getText());
        oPdr.setUbicacion_pdr(jTextFieldUbicacion_Pdr.getText());
        oPdr.setDescripcion_pdr(jTextFieldDescripcion_Pdr.getText());
        oPdr.setPiso_pdr(jTextFieldPiso_Pdr.getText());
        
        return oPdr;
        
    }
    public void limpiar(){
        jTextFieldId_Pdr.setText("");
        jTextFieldNombre_Pdr.setText("");
        jTextFieldUbicacion_Pdr.setText("");
        jTextFieldDescripcion_Pdr.setText("");
        jTextFieldPiso_Pdr.setText("");
        
        jButtonAgregar_Pdr.setEnabled(true);
        jButtonModificar_Pdr.setEnabled(false);
        jButtonEliminar_Pdr.setEnabled(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPdr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPdr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPdr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPdr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPdr().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregar_Pdr;
    private javax.swing.JButton jButtonCancelar_Pdr;
    private javax.swing.JButton jButtonEliminar_Pdr;
    private javax.swing.JButton jButtonModificar_Pdr;
    private javax.swing.JButton jButtonSalir_Pdr;
    private javax.swing.JButton jButtonVAM_Pdr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePdr;
    private javax.swing.JTextField jTextFieldDescripcion_Pdr;
    private javax.swing.JTextField jTextFieldId_Pdr;
    private javax.swing.JTextField jTextFieldNombre_Pdr;
    private javax.swing.JTextField jTextFieldPiso_Pdr;
    private javax.swing.JTextField jTextFieldUbicacion_Pdr;
    // End of variables declaration//GEN-END:variables
}
