/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package duocucmaps.gui;

import duocucmaps.bl.servicioBL;
import duocucmaps.dal.conexion;
import java.sql.ResultSet;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 56964
 */
public class frmServicio extends javax.swing.JFrame {
    DefaultTableModel modelo;

    /**
     * Creates new form frmServicio
     */
    public frmServicio() {
        initComponents();
        setLocationRelativeTo(this);
        String[] titulos = {"ID", "Nombre", "Ubicación", "Descripción", "Piso"};
        modelo = new DefaultTableModel(null, titulos);
        jTableServicio.setModel(modelo);
        this.mostrarDatos();
        this.limpiar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableServicio = new javax.swing.JTable();
        jButtonSalir_Servicio = new javax.swing.JButton();
        jButtonVAM_Servicio = new javax.swing.JButton();
        jButtonAgregar_Servicio = new javax.swing.JButton();
        jButtonCancelar_Servicio = new javax.swing.JButton();
        jButtonEliminar_Servicio = new javax.swing.JButton();
        jButtonModificar_Servicio = new javax.swing.JButton();
        jTextFieldUbicacion_Servicio = new javax.swing.JTextField();
        jTextFieldNombre_Servicio = new javax.swing.JTextField();
        jTextFieldId_Servicio = new javax.swing.JTextField();
        jTextFieldDescripcion_Servicio = new javax.swing.JTextField();
        jTextFieldPiso_Servicio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duocucmaps/recursos/DUOC-UCBlancoV.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(34, 34, 34))
        );

        jTableServicio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableServicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableServicioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableServicio);

        jButtonSalir_Servicio.setText("Salir");
        jButtonSalir_Servicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalir_ServicioActionPerformed(evt);
            }
        });

        jButtonVAM_Servicio.setText("Volver al menú");
        jButtonVAM_Servicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVAM_ServicioActionPerformed(evt);
            }
        });

        jButtonAgregar_Servicio.setText("Agregar");
        jButtonAgregar_Servicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregar_ServicioActionPerformed(evt);
            }
        });

        jButtonCancelar_Servicio.setText("Cancelar");
        jButtonCancelar_Servicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelar_ServicioActionPerformed(evt);
            }
        });

        jButtonEliminar_Servicio.setText("Eliminar");
        jButtonEliminar_Servicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminar_ServicioActionPerformed(evt);
            }
        });

        jButtonModificar_Servicio.setText("Modificar");
        jButtonModificar_Servicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificar_ServicioActionPerformed(evt);
            }
        });

        jTextFieldId_Servicio.setEditable(false);

        jTextFieldPiso_Servicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPiso_ServicioActionPerformed(evt);
            }
        });

        jLabel2.setText("Descripción:");

        jLabel3.setText("Piso:");

        jLabel4.setText("ID:");

        jLabel5.setText("Nombre:");

        jLabel6.setText("Ubicación:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("MANTENEDOR DE SERVICIOS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldId_Servicio, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jTextFieldNombre_Servicio, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldUbicacion_Servicio, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldDescripcion_Servicio, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPiso_Servicio, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(274, 274, 274)
                                    .addComponent(jButtonVAM_Servicio)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButtonSalir_Servicio))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(35, 35, 35)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jButtonAgregar_Servicio)
                                            .addGap(40, 40, 40)
                                            .addComponent(jButtonEliminar_Servicio))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGap(225, 225, 225)
                                            .addComponent(jButtonModificar_Servicio)
                                            .addGap(38, 38, 38)
                                            .addComponent(jButtonCancelar_Servicio))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(38, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldId_Servicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNombre_Servicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUbicacion_Servicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDescripcion_Servicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPiso_Servicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAgregar_Servicio)
                    .addComponent(jButtonEliminar_Servicio)
                    .addComponent(jButtonModificar_Servicio)
                    .addComponent(jButtonCancelar_Servicio))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSalir_Servicio)
                    .addComponent(jButtonVAM_Servicio))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldPiso_ServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPiso_ServicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPiso_ServicioActionPerformed

    private void jButtonAgregar_ServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregar_ServicioActionPerformed
        // TODO add your handling code here:
        conexion objConexion = new conexion();
        
        servicioBL oServicio = recuperarDatosGUI();
        
        String strSentenciaInsert = String.format("INSERT INTO Servicio (id_servicio, nombre_servicio, ubicacion_servicio, descripcion_servicio, piso_servicio)"
                + "VALUES (null, '%s', '%s', '%s', '%s')", oServicio.getNombre_servicio(), oServicio.getUbicacion_servicio(), oServicio.getDescripcion_servicio(), oServicio.getPiso_servicio());
        
        objConexion.ejecutarSentenciaSQL(strSentenciaInsert);
        this.mostrarDatos();
        this.limpiar();
    }//GEN-LAST:event_jButtonAgregar_ServicioActionPerformed

    private void jTableServicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableServicioMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount () == 1){
            JTable receptor = (JTable)evt.getSource();
            jTextFieldId_Servicio.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),0).toString());
            jTextFieldNombre_Servicio.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),1).toString());
            jTextFieldUbicacion_Servicio.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),2).toString());
            jTextFieldDescripcion_Servicio.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),3).toString());
            jTextFieldPiso_Servicio.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),4).toString());
        }
        jButtonAgregar_Servicio.setEnabled(false);
        jButtonModificar_Servicio.setEnabled(true);
        jButtonEliminar_Servicio.setEnabled(true);
    }//GEN-LAST:event_jTableServicioMouseClicked

    private void jButtonEliminar_ServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminar_ServicioActionPerformed
        // TODO add your handling code here:
        conexion objConexion = new conexion();
        
        servicioBL oServicio = recuperarDatosGUI();
        
        String strSentenciaInsert = String.format("DELETE FROM Servicio WHERE id_servicio = %d", oServicio.getId_servicio());
        
        objConexion.ejecutarSentenciaSQL(strSentenciaInsert);
        this.mostrarDatos();
        this.limpiar();
    }//GEN-LAST:event_jButtonEliminar_ServicioActionPerformed

    private void jButtonModificar_ServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificar_ServicioActionPerformed
        // TODO add your handling code here:
        conexion objConexion = new conexion();
        
        servicioBL oServicio = recuperarDatosGUI();
        
        String strSentenciaInsert = String.format("UPDATE Servicio SET nombre_servicio = '%s'," + "ubicacion_servicio = '%s'," + "descripcion_servicio = '%s'," + "piso_servicio = '%s' WHERE id_servicio = %d"
                ,oServicio.getNombre_servicio(), oServicio.getUbicacion_servicio(), oServicio.getDescripcion_servicio(), oServicio.getPiso_servicio(), oServicio.getId_servicio());
        
        objConexion.ejecutarSentenciaSQL(strSentenciaInsert);
        this.mostrarDatos();
        this.limpiar();
    }//GEN-LAST:event_jButtonModificar_ServicioActionPerformed

    private void jButtonCancelar_ServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelar_ServicioActionPerformed
        // TODO add your handling code here:
        this.limpiar();
    }//GEN-LAST:event_jButtonCancelar_ServicioActionPerformed

    private void jButtonSalir_ServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalir_ServicioActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonSalir_ServicioActionPerformed

    private void jButtonVAM_ServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVAM_ServicioActionPerformed
        // TODO add your handling code here:
        this.hide();
        Mantenedor mn = new Mantenedor();
        mn.setVisible(true);
    }//GEN-LAST:event_jButtonVAM_ServicioActionPerformed
    public void mostrarDatos() {
        while(modelo.getRowCount()>0){
            modelo.removeRow(0);
        }
        conexion objConexion = new conexion();
        
        try {
            ResultSet resultado = objConexion.consultarRegistros("SELECT * FROM Servicio");
            while (resultado.next()) {
                System.out.println(resultado.getString("id_servicio"));
                System.out.println(resultado.getString("nombre_servicio"));
                System.out.println(resultado.getString("ubicacion_servicio"));
                System.out.println(resultado.getString("descripcion_servicio"));
                System.out.println(resultado.getString("piso_servicio"));
                
                Object[] oServicio = {resultado.getString("id_servicio"), resultado.getString("nombre_servicio"), resultado.getString("ubicacion_servicio"), resultado.getString("descripcion_servicio"), resultado.getString("piso_servicio")};
                
                modelo.addRow(oServicio);
            }
        }
        catch (Exception e){
            System.out.println(e);
        }
    }
    
    public servicioBL recuperarDatosGUI() {
        servicioBL oServicio = new servicioBL();
        int id_servicio = (jTextFieldId_Servicio.getText().isEmpty()) ?0 : Integer.parseInt(jTextFieldId_Servicio.getText());
        
        oServicio.setId_servicio(id_servicio);
        oServicio.setNombre_servicio(jTextFieldNombre_Servicio.getText());
        oServicio.setUbicacion_servicio(jTextFieldUbicacion_Servicio.getText());
        oServicio.setDescripcion_servicio(jTextFieldDescripcion_Servicio.getText());
        oServicio.setPiso_servicio(jTextFieldPiso_Servicio.getText());
        
        return oServicio;
        
    }
    public void limpiar(){
        jTextFieldId_Servicio.setText("");
        jTextFieldNombre_Servicio.setText("");
        jTextFieldUbicacion_Servicio.setText("");
        jTextFieldDescripcion_Servicio.setText("");
        jTextFieldPiso_Servicio.setText("");
        
        jButtonAgregar_Servicio.setEnabled(true);
        jButtonModificar_Servicio.setEnabled(false);
        jButtonEliminar_Servicio.setEnabled(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmServicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregar_Servicio;
    private javax.swing.JButton jButtonCancelar_Servicio;
    private javax.swing.JButton jButtonEliminar_Servicio;
    private javax.swing.JButton jButtonModificar_Servicio;
    private javax.swing.JButton jButtonSalir_Servicio;
    private javax.swing.JButton jButtonVAM_Servicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableServicio;
    private javax.swing.JTextField jTextFieldDescripcion_Servicio;
    private javax.swing.JTextField jTextFieldId_Servicio;
    private javax.swing.JTextField jTextFieldNombre_Servicio;
    private javax.swing.JTextField jTextFieldPiso_Servicio;
    private javax.swing.JTextField jTextFieldUbicacion_Servicio;
    // End of variables declaration//GEN-END:variables
}
