/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package duocucmaps.gui;
import duocucmaps.bl.salaBL;
import duocucmaps.dal.conexion;
import java.sql.ResultSet;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 56964
 */
public class frmSala extends javax.swing.JFrame {
    DefaultTableModel modelo;
    

    /**
     * Creates new form frmSala
     */
    public frmSala() {
        initComponents();
        setLocationRelativeTo(this);
        String[] titulos = {"ID", "Nombre", "Escuela", "Ubicación", "Descripción", "Piso"};
        modelo = new DefaultTableModel(null, titulos);
        jTableSala.setModel(modelo);
        this.mostrarDatos();
        this.limpiar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jButtonAgregar_Sala = new javax.swing.JButton();
        jButtonEliminar_Sala = new javax.swing.JButton();
        jButtonModificar_Sala = new javax.swing.JButton();
        jButtonCancelar_Sala = new javax.swing.JButton();
        jTextFieldId_Sala = new javax.swing.JTextField();
        jTextFieldNombre_Sala = new javax.swing.JTextField();
        jTextFieldEscuela_Sala = new javax.swing.JTextField();
        jTextFieldUbicacion_Sala = new javax.swing.JTextField();
        jTextFieldDescripcion_Sala = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldPiso_Sala = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableSala = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jButtonSalir_Sala = new javax.swing.JButton();
        jButtonVAM_Sala = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duocucmaps/recursos/DUOC-UCBlancoV.png"))); // NOI18N
        jLabel7.setText("jLabel7");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(31, 31, 31))
        );

        jButtonAgregar_Sala.setText("Agregar");
        jButtonAgregar_Sala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregar_SalaActionPerformed(evt);
            }
        });

        jButtonEliminar_Sala.setText("Eliminar");
        jButtonEliminar_Sala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminar_SalaActionPerformed(evt);
            }
        });

        jButtonModificar_Sala.setText("Modificar");
        jButtonModificar_Sala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificar_SalaActionPerformed(evt);
            }
        });

        jButtonCancelar_Sala.setText("Cancelar");
        jButtonCancelar_Sala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelar_SalaActionPerformed(evt);
            }
        });

        jTextFieldId_Sala.setEditable(false);

        jTextFieldNombre_Sala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombre_SalaActionPerformed(evt);
            }
        });

        jLabel1.setText("ID:");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Escuela:");

        jLabel4.setText("Ubicación:");

        jLabel5.setText("Descripción:");

        jLabel6.setText("Piso:");

        jTableSala.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableSala.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableSalaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableSala);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("MANTENEDOR DE SALAS");

        jButtonSalir_Sala.setBackground(new java.awt.Color(255, 255, 255));
        jButtonSalir_Sala.setText("Salir");
        jButtonSalir_Sala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalir_SalaActionPerformed(evt);
            }
        });

        jButtonVAM_Sala.setText("Volver al menú");
        jButtonVAM_Sala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVAM_SalaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(140, 140, 140))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButtonAgregar_Sala)
                                    .addGap(40, 40, 40)
                                    .addComponent(jButtonEliminar_Sala)
                                    .addGap(43, 43, 43)
                                    .addComponent(jButtonModificar_Sala)
                                    .addGap(40, 40, 40)
                                    .addComponent(jButtonCancelar_Sala)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel3)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jLabel4))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel6)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldDescripcion_Sala, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                                    .addComponent(jTextFieldUbicacion_Sala)
                                    .addComponent(jTextFieldEscuela_Sala, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldNombre_Sala)
                                    .addComponent(jTextFieldId_Sala)
                                    .addComponent(jTextFieldPiso_Sala))))
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonVAM_Sala)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSalir_Sala)
                        .addGap(36, 36, 36))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldId_Sala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNombre_Sala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEscuela_Sala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUbicacion_Sala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDescripcion_Sala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPiso_Sala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAgregar_Sala)
                    .addComponent(jButtonEliminar_Sala)
                    .addComponent(jButtonModificar_Sala)
                    .addComponent(jButtonCancelar_Sala))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVAM_Sala)
                    .addComponent(jButtonSalir_Sala))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNombre_SalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombre_SalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombre_SalaActionPerformed

    private void jButtonAgregar_SalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregar_SalaActionPerformed
        // TODO add your handling code here:
        conexion objConexion = new conexion();
        
        salaBL oSala = recuperarDatosGUI();
        
        String strSentenciaInsert = String.format("INSERT INTO Sala (id_sala, nombre_sala, escuela_sala, ubicacion_sala, descripcion_sala, piso_sala)"
                + "VALUES (null, '%s', '%s', '%s', '%s', '%s')", oSala.getNombre_sala(), oSala.getEscuela_sala(), oSala.getUbicacion_sala(), oSala.getDescripcion_sala(), oSala.getPiso_sala());
        
        objConexion.ejecutarSentenciaSQL(strSentenciaInsert);
        this.mostrarDatos();
        this.limpiar();
    }//GEN-LAST:event_jButtonAgregar_SalaActionPerformed

    private void jTableSalaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSalaMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount () == 1){
            JTable receptor = (JTable)evt.getSource();
            jTextFieldId_Sala.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),0).toString());
            jTextFieldNombre_Sala.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),1).toString());
            jTextFieldEscuela_Sala.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),2).toString());
            jTextFieldUbicacion_Sala.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),3).toString());
            jTextFieldDescripcion_Sala.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),4).toString());
            jTextFieldPiso_Sala.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),5).toString());
        }
        jButtonAgregar_Sala.setEnabled(false);
        jButtonModificar_Sala.setEnabled(true);
        jButtonEliminar_Sala.setEnabled(true);
    }//GEN-LAST:event_jTableSalaMouseClicked

    private void jButtonEliminar_SalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminar_SalaActionPerformed
        // TODO add your handling code here:
        conexion objConexion = new conexion();
        
        salaBL oSala = recuperarDatosGUI();
        
        String strSentenciaInsert = String.format("DELETE FROM Sala WHERE id_sala = %d", oSala.getId_sala());
        
        objConexion.ejecutarSentenciaSQL(strSentenciaInsert);
        this.mostrarDatos();
        this.limpiar();
    }//GEN-LAST:event_jButtonEliminar_SalaActionPerformed

    private void jButtonModificar_SalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificar_SalaActionPerformed
        // TODO add your handling code here:
        conexion objConexion = new conexion();
        
        salaBL oSala = recuperarDatosGUI();
        
        String strSentenciaInsert = String.format("UPDATE Sala SET nombre_sala = '%s'," + "escuela_sala = '%s'," + "ubicacion_sala = '%s'," + "descripcion_sala = '%s'," + "piso_sala = '%s' WHERE id_sala = %d"
                ,oSala.getNombre_sala(), oSala.getEscuela_sala(), oSala.getUbicacion_sala(), oSala.getDescripcion_sala(), oSala.getPiso_sala(), oSala.getId_sala());
        
        objConexion.ejecutarSentenciaSQL(strSentenciaInsert);
        this.mostrarDatos();
        this.limpiar();
    }//GEN-LAST:event_jButtonModificar_SalaActionPerformed

    private void jButtonCancelar_SalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelar_SalaActionPerformed
        // TODO add your handling code here:
        this.limpiar();
    }//GEN-LAST:event_jButtonCancelar_SalaActionPerformed

    private void jButtonSalir_SalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalir_SalaActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonSalir_SalaActionPerformed

    private void jButtonVAM_SalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVAM_SalaActionPerformed
        // TODO add your handling code here:
        this.hide();
        Mantenedor mn = new Mantenedor();
        mn.setVisible(true);
    }//GEN-LAST:event_jButtonVAM_SalaActionPerformed
    public void mostrarDatos() {
        while(modelo.getRowCount()>0){
            modelo.removeRow(0);
        }
        conexion objConexion = new conexion();
        
        try {
            ResultSet resultado = objConexion.consultarRegistros("SELECT * FROM Sala");
            while (resultado.next()) {
                System.out.println(resultado.getString("id_sala"));
                System.out.println(resultado.getString("nombre_sala"));
                System.out.println(resultado.getString("escuela_sala"));
                System.out.println(resultado.getString("ubicacion_sala"));
                System.out.println(resultado.getString("descripcion_sala"));
                System.out.println(resultado.getString("piso_sala"));
                
                Object[] oSala = {resultado.getString("id_sala"), resultado.getString("nombre_sala"), resultado.getString("escuela_sala"), resultado.getString("ubicacion_sala"), resultado.getString("descripcion_sala"), resultado.getString("piso_sala")};
                
                modelo.addRow(oSala);
            }
        }
        catch (Exception e){
            System.out.println(e);
        }
    }
    
    public salaBL recuperarDatosGUI() {
        salaBL oSala = new salaBL();
        int id_sala = (jTextFieldId_Sala.getText().isEmpty()) ?0 : Integer.parseInt(jTextFieldId_Sala.getText());
        
        oSala.setId_sala(id_sala);
        oSala.setNombre_sala(jTextFieldNombre_Sala.getText());
        oSala.setEscuela_sala(jTextFieldEscuela_Sala.getText());
        oSala.setUbicacion_sala(jTextFieldUbicacion_Sala.getText());
        oSala.setDescripcion_sala(jTextFieldDescripcion_Sala.getText());
        oSala.setPiso_sala(jTextFieldPiso_Sala.getText());
        
        return oSala;
        
    }
    public void limpiar(){
        jTextFieldId_Sala.setText("");
        jTextFieldNombre_Sala.setText("");
        jTextFieldEscuela_Sala.setText("");
        jTextFieldUbicacion_Sala.setText("");
        jTextFieldDescripcion_Sala.setText("");
        jTextFieldPiso_Sala.setText("");
        
        jButtonAgregar_Sala.setEnabled(true);
        jButtonModificar_Sala.setEnabled(false);
        jButtonEliminar_Sala.setEnabled(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSala().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregar_Sala;
    private javax.swing.JButton jButtonCancelar_Sala;
    private javax.swing.JButton jButtonEliminar_Sala;
    private javax.swing.JButton jButtonModificar_Sala;
    private javax.swing.JButton jButtonSalir_Sala;
    private javax.swing.JButton jButtonVAM_Sala;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableSala;
    private javax.swing.JTextField jTextFieldDescripcion_Sala;
    private javax.swing.JTextField jTextFieldEscuela_Sala;
    private javax.swing.JTextField jTextFieldId_Sala;
    private javax.swing.JTextField jTextFieldNombre_Sala;
    private javax.swing.JTextField jTextFieldPiso_Sala;
    private javax.swing.JTextField jTextFieldUbicacion_Sala;
    // End of variables declaration//GEN-END:variables
}
